// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIMhE5mSJhVy9x3d7-2ms2aakn1gLzCYY',
    appId: '1:891403388969:web:b7a3081bf6fd77cf11b438',
    messagingSenderId: '891403388969',
    projectId: 'beestore-erz',
    authDomain: 'beestore-erz.firebaseapp.com',
    storageBucket: 'beestore-erz.appspot.com',
    measurementId: 'G-G7TLYN1Q02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJI0FiWZCr37D6iagZLbTq8_ZZv4t6xh0',
    appId: '1:891403388969:android:3436a4e5e5a0d9db11b438',
    messagingSenderId: '891403388969',
    projectId: 'beestore-erz',
    storageBucket: 'beestore-erz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBrgHJfv5QNN_X-_-vbVSLzgd2JTyOJ90',
    appId: '1:891403388969:ios:8a7fd2869429b5e911b438',
    messagingSenderId: '891403388969',
    projectId: 'beestore-erz',
    storageBucket: 'beestore-erz.appspot.com',
    iosBundleId: 'com.example.beeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBrgHJfv5QNN_X-_-vbVSLzgd2JTyOJ90',
    appId: '1:891403388969:ios:8a7fd2869429b5e911b438',
    messagingSenderId: '891403388969',
    projectId: 'beestore-erz',
    storageBucket: 'beestore-erz.appspot.com',
    iosBundleId: 'com.example.beeStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIMhE5mSJhVy9x3d7-2ms2aakn1gLzCYY',
    appId: '1:891403388969:web:9638b4126365bd8a11b438',
    messagingSenderId: '891403388969',
    projectId: 'beestore-erz',
    authDomain: 'beestore-erz.firebaseapp.com',
    storageBucket: 'beestore-erz.appspot.com',
    measurementId: 'G-MT798KR2MJ',
  );
}
